### ISSUE TITLE
tools: Handle the FileNotFoundError: [Errno 2] No such file or directory: 'Figure_0.png' error

### ISSUE THREAD

**Issue by ldorau** [pmem/rpma#1526]
Add the message with the explanation for the following error:
```
[root@NC02 perf]# ./report_create.py --bench results/bench.json --report report.json
Traceback (most recent call last):
File "./report_create.py", line 71, in <module>
main()
File "./report_create.py", line 60, in main
report = Report(ENV, bench, args.report)
File "/home/fjy/rpma-devel-new-python/tools/perf/lib/report/base.py", line 169, in __init__
self.__parts = self.__load_parts(env, bench)
File "/home/fjy/rpma-devel-new-python/tools/perf/lib/report/base.py", line 108, in __load_parts
shutil.copy(self.__variables['configuration']['schematic'],
File "/usr/lib64/python3.8/shutil.py", line 415, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/usr/lib64/python3.8/shutil.py", line 261, in copyfile
with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'Figure_0.png'
```

**Comment by osalyk** [comment]
https://github.com/pmem/rpma/commit/74802b63ea0a45256c093dd0f12dc0027d0d2e7e#diff-1c56e77f6d240fee2d43c395d83ba0a9ce71c90cce3e58b6e5df3fd68e916522L153
